config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :users, only: %i[new create show index]

  root 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
# app/models/idea
class Idea < ApplicationRecord
  validates_presence_of :title, :description
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ideas_controller.rb
# app/controllers/ideas_controller
class IdeasController < ApplicationController
  before_action :set_idea, only: %i[show edit update destroy]

  def index
    @ideas = Idea.all
  end

  def show; end

  def new
    @idea = Idea.new
  end

  def edit; end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      redirect_to idea_path(@idea), notice: 'Idea was successfully created.'
    else
      render :new
    end
  end

  def update
    if @idea.update(idea_params)
      redirect_to idea_path(@idea), notice: 'Idea was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end
end

private
def set_user
  @user = User.find(params[:id])
end

def user_params
  params.require(:user).permit(:username, :email, :password)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h1 Admin Categories

app/views/ideas/_form.html.haml
= form_for @idea do |f|
  - if @idea.errors.any?
    #error_explanation
      %h2= "#{pluralize(@idea.errors.count, "error")} prohibited this idea from being saved:"
      %ul
        - @idea.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    %button= link_to 'Cancel', ideas_path
    = f.submit 'Save Idea'

app/views/ideas/edit.html.haml
%h1= "Editing #{@idea.title}"

= render 'form'

app/views/ideas/index.html.haml
%h1 All Ideas
= link_to 'Create a New Idea', new_idea_path

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th

  %tbody
    - @ideas.each do |idea|
      %tr
        %td= link_to "#{idea.title}", idea_path(idea)
        %td= idea.description
        %td= link_to 'Edit', edit_idea_path(idea)
        %td= link_to 'Delete', idea_path(idea), method: :delete, data: { confirm: 'Are you sure?' }

app/views/ideas/new.html.haml
%h1 New idea

= render 'form'

app/views/ideas/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @idea.title
%p
  %b Description:
  = @idea.description

= link_to 'Edit', edit_idea_path(@idea)
\|
= link_to 'Delete', idea_path(@idea), method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideabox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    %button= link_to 'Cancel', users_path
    = f.submit 'Save User'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Username
      %th Email
      %th Password
      %th Password confirmation
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.email
        %td= user.password
        %td= user.password_confirmation
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Email:
  = @user.email
%p
  %b Password:
  = @user.password
%p
  %b Password confirmation:
  = @user.password_confirmation

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path